### PR TITLE
Memory leaks

### PR DESCRIPTION
**Pull request by gwynantj**
The app now runs without memory leaks as far I've been able to see.

I've had the app running for nearly 3 hours and the memory hasn't gone over 60MB.

Also removed some unwanted classes and modified some of the view controllers to be views.

### CODE REVIEW

**Comment by gwynantj** [comment]
image

**Comment by gwynantj** [comment]
I've attached a screen shot of the profiler that's been running for 3 hours ish and as you can see there are no memory leaks and the live bytes is generally quite low.

@chamerling comment the code as necessary then I can go ahead and change it for your needs

**Comment by chamerling** [comment]
Hi @gwynantj 

Will take some time to look at this before the end of the week. Thanks again!

Christophe

**Comment by mkelley33** [comment]
:+1: @gwynantj 

@chamerling this is a great app so thanks for making it open-source and welcoming contributors.

**Comment by chamerling** [comment]
Hi @mkelley33,

Thanks! All contributors are welcome!

Christophe

**Comment by chamerling** [comment]
@gwynantj 

First, looks that there are conflicts and that the merge can not be achieved automatocally from github.
Then, I have some issues on your code, check the screenshot below. Please fix, updated your PR so I can run QuickHub and see your improvments.

capture decran 2013-12-19 a 10 45 49

Christophe

**Comment by gwynantj** [comment]
@chamerling I noticed that your running an older version of XCode so I will look into what the problem is.

**Comment by chamerling** [comment]
@gwynantj yes, need to update this ;)

**Comment by gwynantj** [comment]
@chamerling Ok so I've just downloaded XCode 4.6.3 and fixed the issues with the code....but since XCode 5 bought in a load of changes in the way it constructs nib files it has broken building any apps with XCode 4.6.3.

My suggestion is to upgrade to the latest XCode and try it from there because it's going to be hard to revert all the nib changes. Even if I just open a nib file in the latest XCode it will convert them to the latest format. :(

**Comment by chamerling** [comment]
@gwynantj sorry for that, I will update to Xcode 5 today, need to update OS X before...

**Do not try to fix NIB stuff!**

**Pull request closed without merging**
